platform:ios,'7.0'
project 'VFShoppingMall.xcodeproj'
target :VFShoppingMall do
   pod 'MJRefresh'
   pod 'IQKeyboardManager'
   pod 'SDWebImage'
   pod 'ScreenCompatible_LFL', '~>1.0.0'
   pod 'AFNetworking', '~>3.0.4'
   pod 'SDCycleScrollView','~> 1.6'
   pod 'Masonry', '~> 1.0.1'
end

